### PR TITLE
Automatic partial dump support

### PR DESCRIPTION
**Pull request by CTCaer**
Automatically chooses to use partial dumping if the available sd card space is smaller than the total size of the dump.

Additionally adds some changes to messages, message colors and naming.

This PR is mostly directed to users that do not have a 32GB+ SD Card, or their 32GB card has less actual capacity than the raw eMMC.
So, it could also be used as a reference only.

**TODO**:
- [x] Remove current lba writing retry code and handle the write errors correctly
(all of them are fatal for FatFS and produce corrupt dumps)
- [x] Fix low voltage for some sd cards (done in a separate PR)

### CODE REVIEW

**Comment by nwert** [comment]
I see that you're using FatFS to get the number of available space on the SD card, we already query the SD card size though, see https://github.com/nwert/hekate/blob/master/ipl/sdmmc.c#L750 - I wonder which way is more efficient as in the latter case the FAT doesn't have to be scanned. The only downside I see is when we have multiple partitions on the SD card even though we don't support this yet. What do you think?

**Comment by CTCaer** [comment]
True, but I believe that SD card size is not enough, because available space is more crucial for writing operations. 
(It reports the correct sd card size for me btw, tested 2 Sandisk 32GB, 1 Samsung 128GB). 

Many users have multiple partitions (for example I have 1 exFAT + 1 EXT4). 
Additionally, we should not expect users to format their card every time to clear leftover journal files (if it's enabled in exFAT) and rogue MFT records.
For example in a exFAT partition, after I wrote/deleted/moved around some big files, the filesystem files were using 1.67GB.

It's not efficient for sure (a little bit slow), but every OS does it and it's the only functional way to get available space, I believe.
I can try and play with the FF_FS_NOFSINFO if you want and report back relative speeds and if sizes are correct.

PS:  BTW, the CSD structure you encountered, was probably the version 3 one.

**Comment by CTCaer** [comment]
Users with bad sectors started reporting issues with writes.

The current PR code is wrong though because it must not retry to write again. That's because the error is fatal.

A possible solution is to use the f_write()'s *bw to know how many bytes were written, use f_lseek to rewind the pointer and try some times again.

But let's say we can't write there at all after many retries.
Is there a way to create a file and allocate some megabytes without writing there, so if we retry to write the dump or dump part from start, it will physically fragment the file and skip the bad sectors?

**Comment by CTCaer** [comment]
Made the write to sd error fatal as per FatFs/Diskio guidelines.

We still give users the option to continue though (can produce a corrupted dump) or to abort and try again from the last part.

Lastly, added a message for the 1st free space calculation.

**Comment by nwert** [comment]
I'm curious, how much time is the overhead (are we talking about seconds)? Since in case we want to use it as a bootloader, this could be slightly annyoing, perhaps a compile time switch would be nice.

**Comment by CTCaer** [comment]
Around 2 seconds.

But, there are conditions for this:
- This is only when you call f_getfree() **the first time**.
It does not happening when you mount the volume.
After the first f_getfree(), it's instant.
- For a bootloader's boot functions and read functions, calling f_getfree() is useless. We don't care about free space.

So, imo, we don't need a compile time switch, because we only need this for when we want to write big files. Like what's happening in eMMC dumping.

**Pull request merged**
