### PR TITLE
Added quick impl of autorcm

### PR DESCRIPTION
**Pull request by Reisyukaku**
Corrupts RSA modulus (install) or writes the corrupt byte back (uninstall)

### CODE REVIEW

**Comment by nwert** [comment]
Hey thanks a bunch for participating! This functionality seems kinda dangerous though, did you thoroughly test it?

**Comment by CTCaer** [comment]
It's nice to have it as a developer, because negates the shorting of pin10.
But dunno.  For example, for me it's uneeded, because I use a rail for shorting, which also acts as UART adapter. But others can find it useful.

@Reisyukaku 
To avoid future maintenance, is it possible to change the hardcoded values with a BCT finder-corrupter?
Also, I believe, the option should be a menu that redirects to an android-recovery like dangerous menu:

```
ment_t ment_autorcm[] = {
	MDEF_BACK(),
	MDEF_BACK(),
	MDEF_BACK(),
	MDEF_BACK(),
	MDEF_HANDLER("Install AutoRCM", autorcm_install),
	MDEF_HANDLER("Uninstall AutoRCM", autorcm_unintstall),
	MDEF_BACK(),
	MDEF_BACK(),
	MDEF_BACK(),
	MDEF_BACK(),
	MDEF_END()
};

menu_t menu_autorcm = {
	ment_autorcm,
	"AutoRCM", 0, 0
};

ment_t ment_tools[] = {
	MDEF_BACK(),
	MDEF_HANDLER("Dump RAW eMMC", dump_emmc_rawnand),
	MDEF_HANDLER("Dump eMMC SYS", dump_emmc_system),
	MDEF_HANDLER("Dump eMMC USER", dump_emmc_user),
	MDEF_HANDLER("Dump eMMC BOOT", dump_emmc_boot),
	MDEF_HANDLER("Dump package1", dump_package1),
	MDEF_MENU("AutoRCM", menu_autorcm), //Menu
	MDEF_END()
};
```
And maybe, we can add a MDEF_HEAD(caption) function, for header messages. In this case, "This is a dangerous operation, are you sure?"

**Comment by Reisyukaku** [comment]
It's been tested by multiple people, yea. Although i was thinking on rewriting it a bit to use less code and theoretically be safer. 
@CTCaer Noted, will change stuff around now.

**Comment by Reisyukaku** [comment]
So i xor'd the first byte of the RSA modulus because not only does that cut the codebase in half since i only need one function to toggle it, but also just incase dev units use a different modulus. (Most likely they do)
I'm still under the assumption that there are 4 BCT entries and wont have any less.

**Comment by CTCaer** [comment]
@Reisyukaku great!

Yeah the BCT entries are 4. 
But with your new changes, it's a matter of changing `i < 4`, which is easy and nice.

**Comment by Reisyukaku** [comment]
I barely know the basics of git.. still trying to figure that out without breaking everything.

**Comment by CTCaer** [comment]
The procedure is this (without the // comments):
**git remote add upstream https://github.com/nwert/hekate.git** _//Add upstream repo_
**git fetch upstream** _//Get upstream repo_
**git checkout master** _//Select the branch you want to be rebased, yours is master._
**git rebase upstream/master** _//Rebase the branch onto upstream. This will put your local changes on top._
**git push -f origin master** _//Force push the changes to your hekate fork._

**Comment by Reisyukaku** [comment]
Yea no idea what i did but it commited again for some reason.. merging conflicts is the bane of my existence.

**Pull request closed without merging**
