### PR TITLE
[PKG1][LP0][Backup] Major feature changes

### PR DESCRIPTION
**Pull request by CTCaer**
**[PKG1] Move 1.0.0 secmon to 0x4002B020**
So, it's time to move **1.0.0 secmon**.
If we want to continue having a full featured bootloader, this change is a must.

It will move the secmon to **0x4002B000 + 0x20** (to keep the values addresses aligned).
Additionally, it fixes the relocator patch producing wrong instructions.

So now the payload size limit, to have all fw support, is **160KB - .bss**. (~155 to 158KB)
Additionally, switch back to performance -O2. We don't care anymore

**[PKG1] Add kernel patching**
Add Disable Svc Verification and Enable Debug mode.
Can be enabled via the hekate .ini, using the keys: **fullsvcperm=1**, **debugmode=1** .

Offsets/values from gist and comments in:
https://gist.github.com/roblabla/440f3ceaa0b2d3ca530c2a43fe258420

**[LP0] Inform user that console halted**
Actually this corrects sdram cfg parsing in LP0.
The cfg is missing 3 variables, which ultimately are unused in T210.
Remove them from the LP0 struct and fix configuration saving.

The console sleep, still does not work. But now it tries to enter/leave sleep and halts with backlight on.
At least, this reminds the user to power off the console to not deplete the battery completely.

**[Backup] Add dump verification**
At last a verification on the data read vs data written to ease the mind of the weary.

**[GFX] Fix hedump print last 1-16 bytes**
This fixes hexdump, which didn't print the ASCII of the last 1-16 chars. Also limits the characters into the printables ones.

**Bug fixes, wording, etc**

### CODE REVIEW

**Comment by CTCaer** [comment]
Also:
[HOS] Add sd unmount and proper secmon signaling
No need to signal security monitor that we are at start of booting process or that the BCT was moved.
It now sends the expected, per version, pkg2 available and continues to boot.

**Comment by nwert** [comment]
Oh wow, these are some awesome changes! The 1.0 secmon reloc should be fine, the important part is that we reloc it to somewhere in IRAM that is actually mapped  after the relocator has enabled paging (which happens before the actual copies) and iirc 1.0 maps 40020000 to 40030000. Did you verify this on 1.0?

**Comment by CTCaer** [comment]
That's true and I also saw the sub_400143F0 with the 0x40020000 (which actually happens in all versions). 
This is verified working* on 4 different (user's) switches.

*(By working, I mean the console boots normally, games and homebrew works.)

**Comment by CTCaer** [comment]
Added @roblabla 's Disable SVC verif for 5.X.X

BTW, I'll add some more bufixes here and I am also waiting for 1.0.0 users to test all the standard uses of the console.

**Comment by CTCaer** [comment]
Ok i've added some bugfixes,
replaced host bus speed SDR50 with SDR104 (as per T210 Errata document),
replaced some sdmmc hardcoded values.

Also, I got words back from users and their 1.0.0 switch, behaves completely normal.

**Pull request merged**
