### PR TITLE
Feature/4x

### PR DESCRIPTION
**Pull request by Ced2911**
Fix/clean keygen
Add support for 4xx (patch from Ac_k)
Add support for 5xx (patch from Jan4V fork)
Add dump for package1 (sm/warmboot)

### CODE REVIEW

**Comment by St4rk** [comment]
I'll test once I arrive home, but LGTM :D gj!

**Comment by m4xw** [comment]
I tested it, works fine on 5x.

You've beat me to it, Ced. I literally was about to release my fork yesterday, but I like your changes more and extra dump features come in handy.

Some parts could still use some love, but good that u added the Fw enum (idk why it didnt happen yet), this is a no-brain merge.

**Comment by nwert** [comment]
Finally! While I definitely appreciate the effort, it also seems like you're copying parts from https://github.com/Atmosphere-NX/Atmosphere without giving proper attribution (the bootconfig structure, pkg2 logic). I'd rather we all follow this necessary process, keep this code clean from obvious copying and avoid eventual bad blood/passive aggressive comments in the future. I'm happy to merge this once this problem is fixed and the coding style (same line '{' vs next line '{', etc.) has been normalised a bit.

**Comment by m4xw** [comment]
Didn't atmosphere just get them from a firmware dump + IDA either?
Kinda split with my opinion on the credit topic, so unless its very obvious, I have some reasonable doubt.

**Comment by Ced2911** [comment]
I did some cleanup (removed unused code from bootconfig/pkg2/sha256)

**Comment by shahmirn** [comment]
What are the chances of getting 3.0.1 support?

**Comment by St4rk** [comment]
^ 
It's already supported, I don't think we have a patchset though, but, I can try to provide it this week :-)

**Comment by shahmirn** [comment]
That'd be great. I compiled and tried running it, but after picking cfw, I
got a pink screen.

**Comment by Ced2911** [comment]
I'm still trying to fix some keyslot and sha issues, but i'm lacking free time :(

**Comment by Stoned1337** [comment]
OK thanks. I hope you get it quickly. I have no desire to update but it is also difficult to wait. : D

**Pull request merged**
