### PR TITLE
Fix 3.0.0

### PR DESCRIPTION
**Pull request by jsaowji**
I don't know if my changes break 1.0.0/2.X.X/4.X.X. I only tested them on 3.0.0 and 5.0.2.

### CODE REVIEW

**Comment by nwert** [comment]
Did anyone test this on the other firmwares?

**Comment by CTCaer** [comment]
My 1.0.0 switch is wiped and I'm still trying to recreate everything, so I can't help.
I can confirm the following:
3.0.0 (user)
4.0.0 (old backup)
4.0.1 (user)
5.0.2

So we need confirmation for
1.0.0
2.x
3.0.1-2(needs se patches)

**Comment by atkinchris** [comment]
Tested this on `3.0.2` - black screen, no boot.

**Comment by nwert** [comment]
I see, thanks for testing! The thing is, we don't need the SE patches if the keyslots are configures properly - which we should do then. I'll try to look into it if I find some time.

**Comment by Seddigirl** [comment]
tested on 3.0.0, looks like it boots normally but never actually boots same as @atkinchris

**Comment by atkinchris** [comment]
>if the keyslots are configures properly

What would configuring the keyslots bring us? I assume you're talking about http://switchbrew.org/index.php?title=Cryptosystem#Package1ldr

**Comment by CTCaer** [comment]
So, this in the end, changes the total support to every firmware, except 3.0.1/3.0.2.

@jsaowji can you rebase it to latest commit?

**Comment by Seddigirl** [comment]
@CTCaer it's not working on 3.0.0 which it's claiming to fix so every firmware, except 3.x

**Comment by CTCaer** [comment]
@Seddigirl 
You sure about that? Many users reported it as working.
What files did you used?

**Comment by CTCaer** [comment]
@Seddigirl 
What you ended up doing with the keyslots in the end is what this commit does.
The only change is that you added keyslots 13 and 14 for 4.x and 5.x,
which we should check if they are really needed for anything and make a PR.

The actual problem was that you were trying the latest AMS. The one that works is more than 20 days older and Atmosphere changed a whole lot and it's more depended of its other parts.
I believe that if you load more kip files that the new loader and sm need, it should boot.

**Comment by CTCaer** [comment]
Superseded by https://github.com/nwert/hekate/pull/27

**Pull request closed without merging**
